// activites.js — registre des activités SEQ05
// Source unique : alimente le site ET les QR codes.
// Les champs objectif/competences/prerequis proviennent de gen_s5_deroules.js
// Les champs titre/question proviennent de gen_s5_fiches_*.js

const ANNEE = "2026";
const SEQ = { code: "seq05", num: "05", nom: "CONCEPTION", titre: "Séquence 05 — Conception" };

const ACTIVITES_SEQ05 = [
  // ---------- 5ÈME ----------
  {
    code: "S5-A01", niveau: "5eme", niveauLabel: "5ème", semaine: "S26",
    phase: "Analyser",
    titre: "Ma maison en NC : du besoin au cahier des charges",
    question: "Comment passer d'un besoin à un cahier des charges que l'architecte peut utiliser ?",
    objectif: "Distinguer besoin/envie, rédiger un CDC simplifié avec contraintes NC, dimensionner ses pièces (+10 % dégagements).",
    competences: ["Thème 3 — Imaginer, concevoir et réaliser une ou des solutions en réponse à un besoin"],
    prerequis: "Aucun (lancement de séquence).",
    materiel: "Fiche S5-A01 · calculatrice",
    fiche: "FICHE_S5-A01_BesoinCDC_5eme",
    ebep: "EBEP_S5-A01_BesoinCDC_5eme",
  },
  {
    code: "S5-A02", niveau: "5eme", niveauLabel: "5ème", semaine: "S27",
    phase: "Représenter",
    titre: "Le plan aux normes : les codes de représentation",
    question: "Comment dessiner un plan que tout le monde comprend, à la bonne échelle ?",
    objectif: "Connaître les symboles architecturaux, maîtriser l'échelle 1/100, produire SON plan conforme au CDC.",
    competences: ["Thème 3 — Imaginer, concevoir et réaliser une ou des solutions en réponse à un besoin"],
    prerequis: "S5-A01 (CDC, surfaces).",
    materiel: "Fiche S5-A02 · papier quadrillé · règle",
    fiche: "FICHE_S5-A02_PlanCodes_5eme",
    ebep: "EBEP_S5-A02_PlanCodes_5eme",
  },
  {
    code: "S5-A03", niveau: "5eme", niveauLabel: "5ème", semaine: "S28",
    phase: "Modéliser",
    titre: "Sweet Home 3D (1) : pièces et murs",
    question: "Comment transformer mon plan papier en maquette numérique ?",
    objectif: "Identifier les 4 zones du logiciel, créer et nommer les pièces, tracer les murs, contrôler les surfaces vs CDC.",
    competences: ["Thème 3 — Imaginer, concevoir et réaliser une ou des solutions en réponse à un besoin"],
    prerequis: "S5-A02 (plan validé).",
    materiel: "Sweet Home 3D · fiche S5-A03 · plan papier de S27",
    fiche: "FICHE_S5-A03_SweetHome1_5eme",
    ebep: "EBEP_S5-A03_SweetHome1_5eme",
  },
  {
    code: "S5-A04", niveau: "5eme", niveauLabel: "5ème", semaine: "S29",
    phase: "Modéliser",
    titre: "Sweet Home 3D (2) : ouvertures, meubles et vues",
    question: "Comment finaliser et présenter ma maquette numérique ?",
    objectif: "Poser portes/fenêtres, meubler, produire le dossier client (captures 2D/3D commentées), s'auto-critiquer.",
    competences: ["Thème 3 — Imaginer, concevoir et réaliser une ou des solutions en réponse à un besoin"],
    prerequis: "S5-A03 (fichier .sh3d avec pièces et murs).",
    materiel: "Sweet Home 3D · fiche S5-A04",
    fiche: "FICHE_S5-A04_SweetHome2_5eme",
    ebep: "EBEP_S5-A04_SweetHome2_5eme",
  },
  {
    code: "S5-A05", niveau: "5eme", niveauLabel: "5ème", semaine: "S30",
    phase: "Fabriquer",
    titre: "La maquette papier de ma pièce préférée (échelle 1/20)",
    question: "Comment passer de la maquette numérique à une maquette en volume, à l'échelle ?",
    objectif: "Convertir à l'échelle 1/20, tracer un patron (sol + 4 murs + languettes), fabriquer, contrôler (±2 mm, équerrage ficelle).",
    competences: ["Thème 3 — Imaginer, concevoir et réaliser une ou des solutions en réponse à un besoin"],
    prerequis: "S5-A04 (dimensions de sa pièce dans Sweet Home).",
    materiel: "Papier 160 g · règle, équerre, ciseaux, colle · ficelle · fiche S5-A05",
    fiche: "FICHE_S5-A05_MaquettePapier_5eme",
    ebep: "EBEP_S5-A05_Maquette_5eme",
  },
  {
    code: "S5-A06", niveau: "5eme", niveauLabel: "5ème", semaine: "S31",
    phase: "Produire",
    titre: "L'atelier de fabrication : imprimante 3D et découpe laser",
    question: "Comment une machine fabrique-t-elle un objet à partir d'un simple fichier ?",
    objectif: "Découvrir les procédés additif et soustractif, les règles de sécurité d'atelier, comparer les procédés.",
    competences: ["Thème 2 — Identifier un dysfonctionnement d'un objet technique et y remédier"],
    prerequis: "S5-A05 (maquettes fabriquées).",
    materiel: "Imprimante 3D · découpeuse laser · fiche S5-A06 · maquettes de S30",
    fiche: "FICHE_S5-A06_Atelier3DLaser_5eme",
    ebep: "EBEP_S5-A06_Atelier_5eme",
  },

  // ---------- 4ÈME ----------
  {
    code: "S5-A01", niveau: "4eme", niveauLabel: "4ème", semaine: "S26",
    phase: "Analyser",
    titre: "Le support de smartphone : du besoin au CDC",
    question: "Comment traduire un besoin flou en cahier des charges précis et vérifiable ?",
    objectif: "Formuler un besoin (3 questions), rédiger un CDC 4 colonnes avec critères mesurables, analyser l'existant.",
    competences: ["Thème 3 — Imaginer, concevoir et réaliser une ou des solutions en réponse à un besoin"],
    prerequis: "Retour du brevet blanc.",
    materiel: "Fiche S5-A01 · réglet",
    fiche: "FICHE_S5-A01_CDC_4eme",
    ebep: "EBEP_S5-A01_CDC_4eme",
  },
  {
    code: "S5-A02", niveau: "4eme", niveauLabel: "4ème", semaine: "S27",
    phase: "Représenter",
    titre: "Croquis coté et perspective",
    question: "Comment représenter une solution pour qu'un autre puisse la fabriquer ?",
    objectif: "Appliquer les règles du croquis coté (mm, cotes uniques), produire 3 solutions dont une perspective, choisir par le CDC.",
    competences: ["Thème 3 — Imaginer, concevoir et réaliser une ou des solutions en réponse à un besoin"],
    prerequis: "S5-A01 (CDC + largeur d'encoche mesurée).",
    materiel: "Fiche S5-A02 · réglet · équerre",
    fiche: "FICHE_S5-A02_CroquisCote_4eme",
    ebep: "EBEP_S5-A02_Croquis_4eme",
  },
  {
    code: "S5-A03", niveau: "4eme", niveauLabel: "4ème", semaine: "S28",
    phase: "Modéliser",
    titre: "SketchUp (1) : formes exactes et poussé-tiré",
    question: "Comment modéliser ma solution aux dimensions exactes de mon croquis ?",
    objectif: "Prendre en main SketchUp (axes, mesures, poussé-tiré), modéliser la base aux cotes exactes, contrôler à l'outil Mètre.",
    competences: ["Thème 3 — Imaginer, concevoir et réaliser une ou des solutions en réponse à un besoin"],
    prerequis: "S5-A02 (croquis coté).",
    materiel: "SketchUp Make 2017 · fiche S5-A03 · croquis coté de S27",
    fiche: "FICHE_S5-A03_SketchUp1_4eme",
    ebep: "EBEP_S5-A03_SketchUp1_4eme",
  },
  {
    code: "S5-A04", niveau: "4eme", niveauLabel: "4ème", semaine: "S29",
    phase: "Modéliser",
    titre: "SketchUp (2) : le modèle final coté",
    question: "Comment finaliser un modèle 3D prêt pour la fabrication ?",
    objectif: "Creuser l'encoche (poussé-tiré négatif), créer la butée, vérifier l'angle, poser les cotes, exporter le dossier.",
    competences: ["Thème 3 — Imaginer, concevoir et réaliser une ou des solutions en réponse à un besoin"],
    prerequis: "S5-A03 (base modélisée aux cotes).",
    materiel: "SketchUp · fiche S5-A04",
    fiche: "FICHE_S5-A04_SketchUp2_4eme",
    ebep: "EBEP_S5-A04_SketchUp2_4eme",
  },
  {
    code: "S5-A05", niveau: "4eme", niveauLabel: "4ème", semaine: "S30",
    phase: "Fabriquer",
    titre: "Prototype carton : je teste ma solution",
    question: "Comment fabriquer un prototype et PROUVER qu'il respecte le CDC ?",
    objectif: "Fabriquer le prototype à l'échelle 1:1 (carton + ficelle), définir et appliquer un protocole de test rigoureux.",
    competences: ["Thème 3 — Imaginer, concevoir et réaliser une ou des solutions en réponse à un besoin"],
    prerequis: "S5-A04 (cotes réelles du modèle).",
    materiel: "Carton · cutter + tapis + règle métal · ficelle · rapporteur · fiche S5-A05",
    fiche: "FICHE_S5-A05_Prototype_4eme",
    ebep: "EBEP_S5-A05_Prototype_4eme",
  },
  {
    code: "S5-A06", niveau: "4eme", niveauLabel: "4ème", semaine: "S31",
    phase: "Produire",
    titre: "Atelier : impression 3D et découpe laser du modèle",
    question: "Comment passe-t-on d'un modèle 3D à un objet réel, et quel procédé choisir ?",
    objectif: "Observer la chaîne numérique CFAO (.skp → .stl → g-code → pièce), comparer additif/soustractif, choisir un procédé pour une série.",
    competences: ["Thème 2 — Identifier un dysfonctionnement d'un objet technique et y remédier"],
    prerequis: "S5-A05 (prototypes testés).",
    materiel: "Imprimante 3D · découpeuse laser · fiche S5-A06",
    fiche: "FICHE_S5-A06_Atelier_4eme",
    ebep: "EBEP_S5-A06_Atelier_4eme",
  },
];

// slug URL : s5-a01-5eme
const slug = a => `${a.code.toLowerCase()}-${a.niveau}`;

// --- SEQ_MERGE_MARKER --- (les séquences migrées sont insérées après ce point)
const SEQ_SEQ02 = { code: "seq02", num: "02", nom: "USAGES", titre: "Séquence 02 — USAGES" };
const ACTIVITES_SEQ02 = [
  {
    code: "S2-A06", niveau: "4eme", niveauLabel: "4ème",
    semaine: "S17",
    phase: "Analyser",
    titre: "L'EXPÉRIENCE UTILISATEUR — CONCEVOIR POUR L'UTILISATEUR",
    question: "PROBLÉMATIQUE : Comment améliorer un objet ou un service numérique sans changer sa fonction d'usage ?",
    objectif: "Identifier les 4 critères UX, auditer deux versions d'une application (accessibilité incluse), produire une maquette d'écran.",
    competences: ["Thème 1 — Décrire les interactions entre un objet ou un système technique, son environnement et les utilisateurs"],
    prerequis: "",
    materiel: "Fiche S2-A06 · PPTX (app A/B)",
    fiche: "FICHE_S2-A06_UX_4eme",
    ebep: null,
  },
  {
    code: "S2-A06", niveau: "5eme", niveauLabel: "5ème",
    semaine: "S17",
    phase: "Analyser",
    titre: "L'EXPÉRIENCE UTILISATEUR — FACILE OU GALÈRE ?",
    question: "PROBLÉMATIQUE : Pourquoi deux objets qui rendent le même service ne sont-ils pas aussi agréables à utiliser ?",
    objectif: "Distinguer usage/utilité/UX, tester des objets réels de la salle, croquer une amélioration d'un objet.",
    competences: ["Thème 1 — Décrire les interactions entre un objet ou un système technique, son environnement et les utilisateurs"],
    prerequis: "",
    materiel: "Fiche S2-A06 · PPTX (distributeurs)",
    fiche: "FICHE_S2-A06_UX_5eme",
    ebep: null,
  },
  {
    code: "S2-A07", niveau: "4eme", niveauLabel: "4ème",
    semaine: "S18",
    phase: "Analyser",
    titre: "COMPARER POUR CHOISIR — LES ORDINATEURS DE LA SALLE 207",
    question: "PROBLÉMATIQUE : Comment comparer objectivement plusieurs objets techniques pour choisir selon un besoin et un budget ?",
    objectif: "Analyser des devis (RAM/SSD), comparer sur des critères chiffrés, recommander un choix argumenté dans un budget donné.",
    competences: ["Thème 1 — Caractériser et choisir un objet ou un système technique selon différents critères"],
    prerequis: "",
    materiel: "Fiche S2-A07 · PPTX (devis)",
    fiche: "FICHE_S2-A07_CHOISIR_4eme",
    ebep: null,
  },
  {
    code: "S2-A07", niveau: "5eme", niveauLabel: "5ème",
    semaine: "S18",
    phase: "Analyser",
    titre: "BIEN CHOISIR UN OBJET TECHNIQUE",
    question: "PROBLÉMATIQUE : Comment choisir l'objet le plus adapté à un besoin, sans se tromper ?",
    objectif: "Lire des fiches produits, comparer selon des critères adaptés au besoin, choisir et justifier avec un budget chiffré.",
    competences: ["Thème 1 — Caractériser et choisir un objet ou un système technique selon différents critères"],
    prerequis: "",
    materiel: "Fiche S2-A07 · PPTX (fiches produits)",
    fiche: "FICHE_S2-A07_CHOISIR_5eme",
    ebep: null,
  },
];
const SEQ_SEQ03 = { code: "seq03", num: "03", nom: "DONNÉES", titre: "Séquence 03 — DONNÉES" };
const ACTIVITES_SEQ03 = [
  {
    code: "S3-A01", niveau: "4eme", niveauLabel: "4ème",
    semaine: "S19",
    phase: "Analyser",
    titre: "DEUX RÉSEAUX AU COLLÈGE : IP, SWITCH, ROUTEUR",
    question: "PROBLÉMATIQUE : Comment les ordinateurs sont-ils organisés en réseaux, et comment deux réseaux différents communiquent-ils ?",
    objectif: "Identifier terminal/switch/routeur/serveur, comprendre la structure d'une adresse IP et la séparation des réseaux.",
    competences: ["Thème 2 — Décrire et caractériser l'organisation interne d'un objet ou d'un système technique et ses échanges avec son environnement (énergies, données)"],
    prerequis: "SEQ01 (périphériques), notion de serveur.",
    materiel: "PPTX (schéma 2 réseaux admin/pédago + structure IP) · fiches S3-A01 (+ EBEP)",
    fiche: "FICHE_S3-A01_DeuxReseaux_4eme",
    ebep: "EBEP_S3-A01_DeuxReseaux_4eme",
  },
  {
    code: "S3-A01", niveau: "5eme", niveauLabel: "5ème",
    semaine: "S19",
    phase: "Analyser",
    titre: "OÙ VONT MES FICHIERS ? — LE RÉSEAU DU COLLÈGE",
    question: "PROBLÉMATIQUE : Comment mon travail peut-il me suivre d'un ordinateur à l'autre au collège ?",
    objectif: "Comprendre que les fichiers sont stockés sur un serveur et que la session identifie l'élève ; créer et retrouver son arborescence.",
    competences: ["Thème 2 — Décrire et caractériser l'organisation interne d'un objet ou d'un système technique et ses échanges avec son environnement (énergies, données)"],
    prerequis: "SEQ01 : enregistrer, nommer un fichier.",
    materiel: "Vidéoprojecteur + support PPTX (schéma réseau salle 207) · salle info · fiches S3-A01 (+ EBEP)",
    fiche: "FICHE_S3-A01_ReseauCollege_5eme",
    ebep: "EBEP_S3-A01_ReseauCollege_5eme",
  },
  {
    code: "S3-A02", niveau: "4eme", niveauLabel: "4ème",
    semaine: "S20",
    phase: "Modéliser",
    titre: "FILIUS (1) : MON RÉSEAU LOCAL OPÉRATIONNEL",
    question: "PROBLÉMATIQUE : Comment construire un réseau local et PROUVER qu'il fonctionne ?",
    objectif: "Construire et tester un réseau local simulé (câble, IP, ping, switch, serveur, ipconfig) et rédiger un compte-rendu de tests.",
    competences: ["Thème 2 — Décrire et caractériser l'organisation interne d'un objet ou d'un système technique et ses échanges avec son environnement (énergies, données)"],
    prerequis: "S3-A01 (IP, switch).",
    materiel: "Filius · PPTX (écrans clés) · fiches S3-A02 (+ EBEP)",
    fiche: "FICHE_S3-A02_Filius1_4eme",
    ebep: "EBEP_S3-A02_Filius1_4eme",
  },
  {
    code: "S3-A02", niveau: "5eme", niveauLabel: "5ème",
    semaine: "S20",
    phase: "Représenter",
    titre: "LE VOYAGE D'UN MESSAGE : DE NOUMÉA À PARIS",
    question: "PROBLÉMATIQUE : Quel chemin parcourt un message qui voyage sur Internet ?",
    objectif: "Décrire le trajet d'un message sur Internet (paquets, serveurs, câbles sous-marins) et situer la NC dans le réseau mondial (Gondwana).",
    competences: ["Thème 2 — Décrire et caractériser l'organisation interne d'un objet ou d'un système technique et ses échanges avec son environnement (énergies, données)"],
    prerequis: "S3-A01 : serveur, réseau local.",
    materiel: "PPTX (carte Gondwana + doc chiffres) · vidéo « fonctionnement du réseau » · fiches S3-A02 (+ EBEP)",
    fiche: "FICHE_S3-A02_VoyageMessage_5eme",
    ebep: "EBEP_S3-A02_VoyageMessage_5eme",
  },
  {
    code: "S3-A03", niveau: "4eme", niveauLabel: "4ème",
    semaine: "S21",
    phase: "Modéliser",
    titre: "FILIUS (2) : UN INTERNET MINIATURE — ROUTEUR ET DNS",
    question: "PROBLÉMATIQUE : Comment des réseaux différents communiquent-ils, et comment une URL devient-elle une adresse IP ?",
    objectif: "Relier deux réseaux par un routeur (passerelles), installer serveur web + DNS et comprendre URL → IP.",
    competences: ["Thème 2 — Décrire et caractériser l'organisation interne d'un objet ou d'un système technique et ses échanges avec son environnement (énergies, données)"],
    prerequis: "S3-A01, S3-A02.",
    materiel: "Filius (+ fichier réseau de secours pré-monté) · PPTX (schéma routeur+DNS) · fiches S3-A03 (+ EBEP) · ÉVAL E1",
    fiche: "FICHE_S3-A03_Filius2_4eme",
    ebep: "EBEP_S3-A03_Filius2_4eme",
  },
  {
    code: "S3-A03", niveau: "5eme", niveauLabel: "5ème",
    semaine: "S21",
    phase: "Analyser",
    titre: "NAVIGATEUR, MOTEUR, SYSTÈME : QUI FAIT QUOI ?",
    question: "PROBLÉMATIQUE : Quels logiciels utilisons-nous vraiment pour aller sur Internet, et qui les possède ?",
    objectif: "Distinguer OS / navigateur / moteur de recherche ; décrire un logiciel par descripteurs ; découvrir le modèle économique des GAFAM.",
    competences: ["Thème 2 — Décrire et caractériser l'organisation interne d'un objet ou d'un système technique et ses échanges avec son environnement (énergies, données)"],
    prerequis: "S3-A01/A02.",
    materiel: "PPTX (étiquettes 3 familles + tableau GAFAM) · salle info · fiches S3-A03 (+ EBEP) · ÉVAL E1 (15 min, DG)",
    fiche: "FICHE_S3-A03_LogicielsGAFAM_5eme",
    ebep: "EBEP_S3-A03_Logiciels_5eme",
  },
  {
    code: "S3-A04", niveau: "4eme", niveauLabel: "4ème",
    semaine: "S22",
    phase: "Analyser",
    titre: "GRATUITS, VRAIMENT ? URL, MOTEURS ET GAFAM",
    question: "PROBLÉMATIQUE : Que payons-nous vraiment quand un service en ligne est « gratuit » ?",
    objectif: "Analyser une URL, identifier les données collectées par les services « gratuits » et leur modèle économique ; préparer un débat argumenté.",
    competences: ["Thème 1 — Décrire les liens entre usages et évolutions technologiques des objets et des systèmes techniques"],
    prerequis: "S3-A03 (DNS, URL → IP).",
    materiel: "PPTX (anatomie URL + tableau GAFAM/données) · salle info · fiches S3-A04 (+ EBEP)",
    fiche: "FICHE_S3-A04_GAFAM_4eme",
    ebep: "EBEP_S3-A04_GAFAM_4eme",
  },
  {
    code: "S3-A04", niveau: "5eme", niveauLabel: "5ème",
    semaine: "S22",
    phase: "Modéliser",
    titre: "FILIUS : JE CONSTRUIS MON PREMIER RÉSEAU",
    question: "PROBLÉMATIQUE : Comment relier des ordinateurs pour qu'ils communiquent, et comment vérifier que ça marche ?",
    objectif: "Simuler un réseau de 2 puis 3 machines (switch), attribuer des adresses IP, tester par ping.",
    competences: ["Thème 2 — Décrire et caractériser l'organisation interne d'un objet ou d'un système technique et ses échanges avec son environnement (énergies, données)"],
    prerequis: "S3-A01 (switch), S3-A02 (adresse IP).",
    materiel: "Filius installé sur les postes · PPTX (écrans clés Filius) · fiches S3-A04 (+ EBEP)",
    fiche: "FICHE_S3-A04_Filius_5eme",
    ebep: "EBEP_S3-A04_Filius_5eme",
  },
];
const SEQ_SEQ04 = { code: "seq04", num: "04", nom: "CYBERSEC", titre: "Séquence 04 — CYBERSEC" };
const ACTIVITES_SEQ04 = [
  {
    code: "S4-A01", niveau: "4eme", niveauLabel: "4ème",
    semaine: "S23",
    phase: "Analyser",
    titre: "PHISHING : L'AUDIT DE LA BOÎTE MAIL",
    question: "PROBLÉMATIQUE : Comment repérer un message piégé, et comment verrouiller ses accès ?",
    objectif: "Repérer les 5 indices d'un message piégé, auditer un corpus de 6 e-mails avec preuves, comprendre la double authentification.",
    competences: ["Thème 1 — Décrire les liens entre usages et évolutions technologiques des objets et des systèmes techniques"],
    prerequis: "SEQ03 : URL, nom de domaine (indispensable pour l'indice « adresse imitée »).",
    materiel: "PPTX (exemple annoté + corpus de 6 e-mails fictifs) · fiches S4-A01 (+ EBEP)",
    fiche: "FICHE_S4-A01_Phishing_4eme",
    ebep: "EBEP_S4-A01_Phishing_4eme",
  },
  {
    code: "S4-A01", niveau: "5eme", niveauLabel: "5ème",
    semaine: "S23",
    phase: "Analyser",
    titre: "MOT DE PASSE : LA CLÉ DE MA VIE NUMÉRIQUE",
    question: "PROBLÉMATIQUE : Comment protéger efficacement mes comptes ?",
    objectif: "Comprendre ce qui rend un mot de passe robuste (longueur, phrase de passe), adopter les règles d'or, définir l'identité numérique.",
    competences: ["Thème 1 — Décrire les liens entre usages et évolutions technologiques des objets et des systèmes techniques"],
    prerequis: "SEQ03 : session, identifiants.",
    materiel: "PPTX (tableau temps de cassage + modèle affichette) · salle info (groupe) · fiches S4-A01 (+ EBEP)",
    fiche: "FICHE_S4-A01_MotsDePasse_5eme",
    ebep: "EBEP_S4-A01_MotsDePasse_5eme",
  },
  {
    code: "S4-A02", niveau: "4eme", niveauLabel: "4ème",
    semaine: "S24",
    phase: "Analyser",
    titre: "TRACES, COOKIES, RGPD : REPRENDRE LA MAIN",
    question: "PROBLÉMATIQUE : Comment nos traces sont-elles exploitées, et quels sont nos droits (RGPD) ?",
    objectif: "Comprendre la mécanique du ciblage publicitaire (cookies), connaître les 4 droits RGPD, paramétrer bannières et applications.",
    competences: ["Thème 1 — Décrire les liens entre usages et évolutions technologiques des objets et des systèmes techniques"],
    prerequis: "S3-A04 (données/GAFAM), S4-A01.",
    materiel: "PPTX (chaîne du ciblage, droits RGPD, bannière cookies) · fiches S4-A02 (+ EBEP) · ÉVAL E2 · consignes brevet blanc à lire en fin de séance",
    fiche: "FICHE_S4-A02_RGPD_4eme",
    ebep: "EBEP_S4-A02_RGPD_4eme",
  },
  {
    code: "S4-A02", niveau: "5eme", niveauLabel: "5ème",
    semaine: "S24",
    phase: "Analyser",
    titre: "MES TRACES NUMÉRIQUES",
    question: "PROBLÉMATIQUE : Quelles traces est-ce que je laisse sur Internet, et qui peut les voir ?",
    objectif: "Distinguer traces volontaires/invisibles, comprendre la persistance d'une publication, paramétrer la confidentialité.",
    competences: ["Thème 1 — Décrire les liens entre usages et évolutions technologiques des objets et des systèmes techniques"],
    prerequis: "S4-A01 (identité numérique).",
    materiel: "PPTX (parcours d'une photo publiée + écran de réglages fictif) · fiches S4-A02 (+ EBEP) · ÉVAL E2",
    fiche: "FICHE_S4-A02_Traces_5eme",
    ebep: "EBEP_S4-A02_Traces_5eme",
  },
  {
    code: "S4-A03", niveau: "5eme", niveauLabel: "5ème",
    semaine: "S25",
    phase: "Produire",
    titre: "CYBERHARCÈLEMENT : RECONNAÎTRE ET RÉAGIR",
    question: "PROBLÉMATIQUE : Comment reconnaître le cyberharcèlement, et que faire — que l'on soit victime ou témoin ?",
    objectif: "Identifier les 3 critères du harcèlement, connaître les réflexes de la victime ET du témoin, mémoriser le 3018.",
    competences: ["Thème 1 — Décrire les liens entre usages et évolutions technologiques des objets et des systèmes techniques"],
    prerequis: "S4-A02.",
    materiel: "PPTX (critères, acteurs/réflexes, modèle d'affiche, 3018) · salle info (groupe) · fiches S4-A03 (+ EBEP)",
    fiche: "FICHE_S4-A03_Cyberharcelement_5eme",
    ebep: "EBEP_S4-A03_Cyberharcelement_5eme",
  },
];
const SEQ_SEQ06 = { code: "seq06", num: "06", nom: "MEI", titre: "Séquence 06 — MEI" };
const ACTIVITES_SEQ06 = [
  {
    code: "S6-A01", niveau: "4eme", niveauLabel: "4ème",
    semaine: "S32",
    phase: "Analyser",
    titre: "mBOT : UN VRAI SYSTÈME À DÉCORTIQUER",
    question: "PROBLÉMATIQUE : Que se passe-t-il entre l'obstacle détecté et le demi-tour du robot ?",
    objectif: "Identifier les constituants du mBot, reconstruire ses chaînes d'information et d'énergie sur système réel.",
    competences: ["Thème 2 — Décrire et caractériser l'organisation interne d'un objet ou d'un système technique et ses échanges avec son environnement (énergies, données)"],
    prerequis: "SEQ02 (chaînes vues sur documents) — ici on passe au RÉEL.",
    materiel: "mBots (4-10, chargés, testés la veille) · PPTX (anatomie + chaînes) · fiches S6-A01 (+ EBEP)",
    fiche: "FICHE_S6-A01_AnatomieMBot_4eme",
    ebep: "EBEP_S6-A01_MBot_4eme",
  },
  {
    code: "S6-A01", niveau: "5eme", niveauLabel: "5ème",
    semaine: "S32",
    phase: "Représenter",
    titre: "LE ROBOT ASPIRATEUR : PROGRAMMER SANS ORDINATEUR",
    question: "PROBLÉMATIQUE : Comment donner des ordres à une machine qui ne comprend que des instructions précises ?",
    objectif: "Définir instruction/séquence/boucle, exécuter et écrire un algorithme en langage naturel sur quadrillage.",
    competences: ["Thème 2 — Comprendre et modifier un programme associé à une fonctionnalité d'un objet ou d'un système technique"],
    prerequis: "Aucun (lancement de séquence).",
    materiel: "PPTX (vocabulaire + grille géante) · fiches S6-A01 (+ EBEP) · règles",
    fiche: "FICHE_S6-A01_Debranche_5eme",
    ebep: "EBEP_S6-A01_Debranche_5eme",
  },
  {
    code: "S6-A02", niveau: "4eme", niveauLabel: "4ème",
    semaine: "S33",
    phase: "Modéliser",
    titre: "mBLOCK : MES PREMIERS PROGRAMMES SUR SYSTÈME RÉEL",
    question: "PROBLÉMATIQUE : Comment programmer un robot réel… et régler ce que la simulation ne montre pas ?",
    objectif: "Téléverser un programme, mesurer une distance parcourue, CALIBRER la rotation 90° par essais successifs, réaliser le carré.",
    competences: ["Thème 3 — Concevoir, écrire, tester et mettre au point un programme"],
    prerequis: "S6-A01.",
    materiel: "mBots + câbles USB/dongles · mBlock installé · zones au sol (adhésif) · réglets · fiches S6-A02 (+ EBEP)",
    fiche: "FICHE_S6-A02_mBlock_4eme",
    ebep: "EBEP_S6-A02_mBlock_4eme",
  },
  {
    code: "S6-A02", niveau: "5eme", niveauLabel: "5ème",
    semaine: "S33",
    phase: "Modéliser",
    titre: "SCRATCH (1) : LE PARCOURS CARRÉ",
    question: "PROBLÉMATIQUE : Comment traduire mon algorithme papier en programme qui s'exécute ?",
    objectif: "Identifier les zones de Scratch, traduire l'algorithme du carré en blocs, réinvestir la boucle, découvrir l'événement.",
    competences: ["Thème 3 — Concevoir, écrire, tester et mettre au point un programme"],
    prerequis: "S6-A01 (algorithme du carré).",
    materiel: "Scratch sur les postes · PPTX (interface + programme en pseudo-blocs) · fiches S6-A02 (+ EBEP) · ÉVAL E5",
    fiche: "FICHE_S6-A02_Scratch1_5eme",
    ebep: "EBEP_S6-A02_Scratch1_5eme",
  },
  {
    code: "S6-A03", niveau: "4eme", niveauLabel: "4ème",
    semaine: "S34",
    phase: "Modéliser",
    titre: "CAPTEURS : ÉVITER UN OBSTACLE, SUIVRE UNE LIGNE",
    question: "PROBLÉMATIQUE : Comment un robot peut-il adapter son comportement à ce que mesurent ses capteurs ?",
    objectif: "Programmer la structure SI/ALORS/SINON avec les capteurs ultrasons et suiveur de ligne, tester sur système réel.",
    competences: ["Thème 3 — Concevoir, écrire, tester et mettre au point un programme"],
    prerequis: "S6-A02 (calibration, téléversement).",
    materiel: "mBots · pistes ligne noire (adhésif ou imprimées, préparées la veille) · obstacles · fiches S6-A03 (+ EBEP) · ÉVAL E5",
    fiche: "FICHE_S6-A03_Capteurs_4eme",
    ebep: "EBEP_S6-A03_Capteurs_4eme",
  },
  {
    code: "S6-A03", niveau: "5eme", niveauLabel: "5ème",
    semaine: "S34",
    phase: "Modéliser",
    titre: "SCRATCH (2) : VARIABLES ET ÉVÉNEMENTS",
    question: "PROBLÉMATIQUE : Comment un programme peut-il mémoriser et faire évoluer une valeur ?",
    objectif: "Créer et faire évoluer une variable (spirale), utiliser un second événement et la condition de rebond.",
    competences: ["Thème 3 — Concevoir, écrire, tester et mettre au point un programme"],
    prerequis: "S6-A02 (boucle, blocs de base).",
    materiel: "Scratch · PPTX (programme spirale + table d'exécution) · fiches S6-A03 (+ EBEP)",
    fiche: "FICHE_S6-A03_Scratch2_5eme",
    ebep: "EBEP_S6-A03_Scratch2_5eme",
  },
  {
    code: "S6-A04", niveau: "4eme", niveauLabel: "4ème",
    semaine: "S35",
    phase: "Produire",
    titre: "LE GRAND DÉFI ROBOT DES MAISONS",
    question: "PROBLÉMATIQUE : Comment mesurer et améliorer objectivement la performance d'un système programmé ?",
    objectif: "Mesurer une performance selon un protocole strict, améliorer par itérations mesurées, analyser vitesse vs précision.",
    competences: ["Thème 3 — Valider les solutions techniques par des simulations ou par des protocoles de tests"],
    prerequis: "S6-A02 (calibration) et S6-A03 (capteurs).",
    materiel: "mBots · parcours au sol (départ, 2 obstacles, arrivée — monté à l'identique pour tous) · chrono officiel · fiches S6-A04 (+ EBEP) · ÉVAL E6 + Kahoot 4ème pour S36",
    fiche: "FICHE_S6-A04_DefiRobot_4eme",
    ebep: "EBEP_S6-A04_Defi_4eme",
  },
  {
    code: "S6-A04", niveau: "5eme", niveauLabel: "5ème",
    semaine: "S35",
    phase: "Produire",
    titre: "LE DÉFI SCRATCH DES MAISONS",
    question: "PROBLÉMATIQUE : Comment concevoir, tester et améliorer un programme qui répond à un cahier des charges ?",
    objectif: "Concevoir, tester et améliorer un programme répondant à un cahier des charges (labyrinthe) ; pratiquer la revue de code.",
    competences: ["Thème 3 — Valider les solutions techniques par des simulations ou par des protocoles de tests"],
    prerequis: "S6-A02/A03.",
    materiel: "Scratch + fond de scène labyrinthe (préparé la veille) · chrono · fiches S6-A04 (+ EBEP) · ÉVAL E6 · Kahoot bilan (S36)",
    fiche: "FICHE_S6-A04_DefiScratch_5eme",
    ebep: "EBEP_S6-A04_Defi_5eme",
  },
];

const SEQUENCES = [
  { SEQ, ACTIVITES: ACTIVITES_SEQ05 },
  { SEQ: SEQ_SEQ02, ACTIVITES: ACTIVITES_SEQ02 },
  { SEQ: SEQ_SEQ03, ACTIVITES: ACTIVITES_SEQ03 },
  { SEQ: SEQ_SEQ04, ACTIVITES: ACTIVITES_SEQ04 },
  { SEQ: SEQ_SEQ06, ACTIVITES: ACTIVITES_SEQ06 },
];

module.exports = { ANNEE, SEQ, ACTIVITES: ACTIVITES_SEQ05, SEQUENCES, slug };
